### ISSUE TITLE
Test mobile UI

### ISSUE THREAD

**Issue by Codeshark-NET** [protontypes/climate-triage#17]

**Comment by andrew** [comment]
There's a couple warnings from pagespeed insights, but mostly looks good: https://pagespeed.web.dev/analysis/https-climatetriage-com/u0m3yrcmis?form_factor=mobile

**Comment by Codeshark-NET** [comment]
Right, maybe we can set the cache policy on the GitHub pages or put Cloudflare in front then, to cache the assets.

**Comment by andrew** [comment]
I think this can be closed now
