### ISSUE TITLE
Security headers missing

### ISSUE THREAD

**Issue by Codeshark-NET** [protontypes/climate-triage#18]
Previously I had to remove the security headers from next.s as it doesn't know how to export those to static files - but perhaps there's a way to enable them on github pages or in the root `layout.tsx`

https://securityheaders.com/?q=https%3A%2F%2Fclimatetriage.com%2F&followRedirects=on

The past headers can be found in next.config.js still. 

CC: @andrew (this is the one I mentioned)

**Comment by andrew** [comment]
I don't believe you can change the headers in github pages, you'd need to proxy the site through another webserver like cloudflare or nginx.

**Comment by Codeshark-NET** [comment]
Moved this to https://github.com/protontypes/climate-triage/issues/20
