### ISSUE TITLE
Use oneliner from OpenSustain.tech instead of GitHub project description

### ISSUE THREAD

**Issue by Ly0n** [protontypes/climate-triage#32]
OpenSustain.tech's project onliners are much cleaner and more consistent than GitHub's project descriptions. They are also shorter, without emojis and as precise as possible. That's why it might be better to use them within the project cards.

**Comment by andrew** [comment]
project.description instead of repository.description I believe

**Comment by Codeshark-NET** [comment]
This was resolved as far as I can tell, closing this. 👍
