### ISSUE TITLE
Add the clothing loop

### ISSUE THREAD

**Issue by lil5** [protontypes/climate-triage#36]
The Clothing Loop is an initiative that offers an easy way for people to swap clothes with others in their own neighborhood.

Please join the movement! After all, if you buy only six items less than you normally would in a year, you save about 40 kilos of CO2 emissions.

https://clothingloop.org/en/about

https://github.com/the-clothing-loop/website

**Comment by Ly0n** [comment]
Here the pull request to the dataset: https://github.com/protontypes/open-sustainable-technology/pull/369
The project should soon be visible on ClimateTriage.com.
