### ISSUE TITLE
Add about text to the site

### ISSUE THREAD

**Issue by Codeshark-NET** [protontypes/climate-triage#9]
We'll need to write a little about what this site is and why it exists.

**Comment by Codeshark-NET** [comment]
Initial text added - up for discussion.

**Comment by Ly0n** [comment]
Here a new abort section: 

> Harness the power of open source collaboration to tackle environmental challenges such as climate change, clean energy, biodiversity, and natural resource conservation. ClimateTriage brings you all the impactful projects that welcome new developers with Help Wanted and Good First Issues. Whether you're an experienced developer, a scientist, or a newcomer looking to contribute, we'll connect you with opportunities to use your skills to create a sustainable future. 

> Still interested but not sure how to get started? Read more about this project and how you can get involved in a impactful way here.
